# 1. THE CLOUD CONNECTION URL
# Format: jdbc:mysql://[YOUR_AIVEN_HOST]:[YOUR_AIVEN_PORT]/defaultdb?sslMode=REQUIRED
spring.datasource.url=jdbc:mysql://edupredict-db-pujansuthar345-ffe1.a.aivencloud.com:16280/defaultdb?sslMode=REQUIRED

# 2. THE CLOUD CREDENTIALS
spring.datasource.username=avnadmin
spring.datasource.password=HIDDEN_FOR_GITHUB

# 3. HIBERNATE SETTINGS
# Use "update" so it automatically builds your tables, but doesn't delete them later!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect